[package]
name = "aries"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-std ="0.4.0"
ark-ff = "0.4.0"
ark-test-curves = {version = "^0.4.0", features = ["bls12_381_curve", "ed_on_bls12_381"]}
ark-serialize = {version = "0.4.0", features = ["derive"]}
byteorder = "1.4"
tempfile = "3.3.0"
plotters = "0.3"
merlin = "3.0.0"

[dev-dependencies]

[patch.crates-io]
ark-ff = {git = "https://github.com/arkworks-rs/algebra"}
ark-test-curves = {git = "https://github.com/arkworks-rs/algebra"}
ark-std = {git = "https://github.com/arkworks-rs/utils"}
ark-serialize = {git = "https://github.com/arkworks-rs/algebra"}
ark-serialize-derive = {git = "https://github.com/arkworks-rs/algebra"}
