[package]
name = "bench-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = { version = "^0.4" }
ark-bls12-381 = { version = "^0.4" }
ark-serialize = { version = "^0.4" }
scribe = { path = "../scribe-snark" }
libc = { version = "^0.2.101" }
